services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    restart: always
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      APP_CONFIG__DB__URL: ${APP_CONFIG__DB__URL}
    depends_on:
      - db

  db:
    image: postgres:17.2-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"

  rabbitmq:
    image: rabbitmq:4-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Kyiv
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
volumes:
  postgres-data:
  rabbitmq-data: