services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    restart: always
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env
    depends_on:
      - db

  db:
    image: postgres:17.2-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"

volumes:
  postgres_data: