"""Add class_num fk.

Revision ID: 1c3e667310e9
Revises: 1e2b0ffa8854
Create Date: 2025-01-10 15:11:12.169264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c3e667310e9"
down_revision: Union[str, None] = "1e2b0ffa8854"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "classes", ["class_num"])
    op.alter_column("students", "second_name", existing_type=sa.VARCHAR(), nullable=True)
    op.create_foreign_key(
        "fk_student_class_num", "students", "classes", ["class_num"], ["class_num"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_student_class_num", "students", type_="foreignkey")
    op.alter_column("students", "second_name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_constraint(None, "classes", type_="unique")
    # ### end Alembic commands ###
