"""Add science subject to marks.

Revision ID: e03d56a3c543
Revises: f0496c7118a9
Create Date: 2025-02-18 18:22:34.727923

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e03d56a3c543"
down_revision: Union[str, None] = "f0496c7118a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("marks", sa.Column("science", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("marks", "science")
    # ### end Alembic commands ###
