"""Id field mixin.

Revision ID: 6252e931d640
Revises: e0cac510a617
Create Date: 2025-02-05 18:12:01.961945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6252e931d640"
down_revision: Union[str, None] = "e0cac510a617"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_classes_class_num"), "classes", ["class_num"])
    op.drop_constraint("students_email_key", "students", type_="unique")
    op.drop_constraint("students_hashed_password_key", "students", type_="unique")
    op.drop_constraint("students_username_key", "students", type_="unique")
    op.create_unique_constraint(op.f("uq_students_email"), "students", ["email"])
    op.create_unique_constraint(
        op.f("uq_students_hashed_password"), "students", ["hashed_password"]
    )
    op.create_unique_constraint(op.f("uq_students_username"), "students", ["username"])
    op.create_foreign_key(
        "fk_student_class_num",
        "students",
        "classes",
        ["class_num"],
        ["class_num"],
        ondelete="CASCADE",
    )
    op.drop_constraint("teachers_class_id_key", "teachers", type_="unique")
    op.drop_constraint("teachers_email_key", "teachers", type_="unique")
    op.drop_constraint("teachers_hashed_password_key", "teachers", type_="unique")
    op.drop_constraint("teachers_username_key", "teachers", type_="unique")
    op.create_unique_constraint(op.f("uq_teachers_class_id"), "teachers", ["class_id"])
    op.create_unique_constraint(op.f("uq_teachers_email"), "teachers", ["email"])
    op.create_unique_constraint(
        op.f("uq_teachers_hashed_password"), "teachers", ["hashed_password"]
    )
    op.create_unique_constraint(op.f("uq_teachers_username"), "teachers", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_teachers_username"), "teachers", type_="unique")
    op.drop_constraint(op.f("uq_teachers_hashed_password"), "teachers", type_="unique")
    op.drop_constraint(op.f("uq_teachers_email"), "teachers", type_="unique")
    op.drop_constraint(op.f("uq_teachers_class_id"), "teachers", type_="unique")
    op.create_unique_constraint("teachers_username_key", "teachers", ["username"])
    op.create_unique_constraint("teachers_hashed_password_key", "teachers", ["hashed_password"])
    op.create_unique_constraint("teachers_email_key", "teachers", ["email"])
    op.create_unique_constraint("teachers_class_id_key", "teachers", ["class_id"])
    op.drop_constraint("fk_student_class_num", "students", type_="foreignkey")
    op.drop_constraint(op.f("uq_students_username"), "students", type_="unique")
    op.drop_constraint(op.f("uq_students_hashed_password"), "students", type_="unique")
    op.drop_constraint(op.f("uq_students_email"), "students", type_="unique")
    op.create_unique_constraint("students_username_key", "students", ["username"])
    op.create_unique_constraint("students_hashed_password_key", "students", ["hashed_password"])
    op.create_unique_constraint("students_email_key", "students", ["email"])
    op.drop_constraint(op.f("uq_classes_class_num"), "classes", type_="unique")
    # ### end Alembic commands ###
