"""Create students table.

Revision ID: ee34c0b00340
Revises: f17ffb33f3f7
Create Date: 2025-06-24 13:40:54.271064

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ee34c0b00340'
down_revision: Union[str, None] = 'f17ffb33f3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'students',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('class_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='fk_student_class_id', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_student_user_id', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    )
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
