"""Add indexes. Some fields small changes.

Revision ID: 7c94ff28489f
Revises: 751fa8369c87
Create Date: 2025-03-28 20:26:13.745264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c94ff28489f'
down_revision: Union[str, None] = '751fa8369c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_classes_class_num', 'classes', type_='unique')
    op.create_index(op.f('ix_classes_class_num'), 'classes', ['class_num'], unique=True)
    op.alter_column('marks', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('uq_marks_student_id', 'marks', type_='unique')
    op.create_index(op.f('ix_marks_student_id'), 'marks', ['student_id'], unique=False)
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.drop_constraint('uq_teachers_class_id', 'teachers', type_='unique')
    op.create_index(op.f('ix_teachers_class_id'), 'teachers', ['class_id'], unique=True)
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_constraint('uq_users_password', 'users', type_='unique')
    op.drop_constraint('uq_users_username', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    op.create_unique_constraint('uq_users_password', 'users', ['password'])
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_class_id'), table_name='teachers')
    op.create_unique_constraint('uq_teachers_class_id', 'teachers', ['class_id'])
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.drop_index(op.f('ix_marks_student_id'), table_name='marks')
    op.create_unique_constraint('uq_marks_student_id', 'marks', ['student_id'])
    op.alter_column('marks', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_classes_class_num'), table_name='classes')
    op.create_unique_constraint('uq_classes_class_num', 'classes', ['class_num'])
    # ### end Alembic commands ###
