"""Create marks-student relationship.

Revision ID: d9a2f1663284
Revises: e728287c55e9
Create Date: 2025-06-24 13:45:23.535844

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd9a2f1663284'
down_revision: Union[str, None] = 'e728287c55e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_marks_student_id'), 'marks', ['student_id'], unique=False)
    op.create_foreign_key('fk_marks_student_id', 'marks', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_marks_student_id', 'marks', type_='foreignkey')
    op.drop_index(op.f('ix_marks_student_id'), table_name='marks')
    op.drop_column('marks', 'student_id')
    # ### end Alembic commands ###
