"""Make class_id in teachers' table unique.

Revision ID: e0cac510a617
Revises: 6b1886afd5a1
Create Date: 2025-01-26 15:00:24.961197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0cac510a617"
down_revision: Union[str, None] = "6b1886afd5a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "teachers", ["class_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teachers", type_="unique")
    # ### end Alembic commands ###
