"""Create teachers table.

Revision ID: e728287c55e9
Revises: ee34c0b00340
Create Date: 2025-06-24 13:41:46.134005

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e728287c55e9'
down_revision: Union[str, None] = 'ee34c0b00340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'teachers',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('class_id', sa.Integer(), nullable=False),
        sa.Column(
            'subject', sa.Enum(
                'MATH', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'HISTORY', 'GEOGRAPHY', 'LITERATURE', name='subject_enum',
            ), nullable=True,
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='fk_teacher_class_id', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_teacher_user_id', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_teachers')),
    )
    op.create_index(op.f('ix_teachers_class_id'), 'teachers', ['class_id'], unique=True)
    op.create_index(op.f('ix_teachers_subject'), 'teachers', ['subject'], unique=False)
    op.create_index(op.f('ix_teachers_user_id'), 'teachers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_user_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_subject'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_class_id'), table_name='teachers')
    op.drop_table('teachers')
    # ### end Alembic commands ###
