"""Add nullable=True to Marks.

Revision ID: 83d3878fcfaa
Revises: 82e8a271ecaa
Create Date: 2025-03-30 19:17:32.247343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d3878fcfaa'
down_revision: Union[str, None] = '82e8a271ecaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marks', 'maths',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('marks', 'english',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('marks', 'physics',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('marks', 'chemistry',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('marks', 'history',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('marks', 'geography',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('marks', 'literature',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marks', 'literature',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('marks', 'geography',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('marks', 'history',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('marks', 'chemistry',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('marks', 'physics',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('marks', 'english',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('marks', 'maths',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
