"""Add marks table.

Revision ID: 622653b06bf6
Revises: e728287c55e9
Create Date: 2025-06-24 13:27:08.567832

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '622653b06bf6'
down_revision: Union[str, None] = 'e728287c55e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'marks',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('student_id', sa.Uuid(), nullable=False),
        sa.Column('maths', sa.Integer(), nullable=True),
        sa.Column('english', sa.Integer(), nullable=True),
        sa.Column('physics', sa.Integer(), nullable=True),
        sa.Column('chemistry', sa.Integer(), nullable=True),
        sa.Column('history', sa.Integer(), nullable=True),
        sa.Column('geography', sa.Integer(), nullable=True),
        sa.Column('literature', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fk_marks_student_id', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_marks')),
    )
    op.create_index(op.f('ix_marks_student_id'), 'marks', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    # ### end Alembic commands ###
