"""Add classes table.

Revision ID: c09df74c879d
Revises: 
Create Date: 2025-06-24 13:26:00.241692

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c09df74c879d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'classes',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('class_num', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_classes')),
    )
    op.create_index(op.f('ix_classes_class_num'), 'classes', ['class_num'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_class_num'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
