"""Add roles column.

Revision ID: f0496c7118a9
Revises: 88982e68e97a
Create Date: 2025-02-13 17:11:07.484888

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0496c7118a9"
down_revision: Union[str, None] = "88982e68e97a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute('CREATE TYPE roleenum AS ENUM (\'student\', \'teacher\', \'superuser\')')

    op.add_column(
        "students",
        sa.Column(
            "role", sa.Enum("STUDENT", "TEACHER", "SUPERUSER", name="roleenum"), nullable=False
        ),
    )
    op.add_column(
        "teachers",
        sa.Column(
            "role", sa.Enum("STUDENT", "TEACHER", "SUPERUSER", name="roleenum"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teachers", "role")
    op.drop_column("students", "role")

    op.execute('DROP TYPE roleenum')
    # ### end Alembic commands ###
