"""Add marks table.

Revision ID: 622653b06bf6
Revises: c09df74c879d
Create Date: 2025-06-24 13:27:08.567832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622653b06bf6'
down_revision: Union[str, None] = 'c09df74c879d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('maths', sa.Integer(), nullable=True),
    sa.Column('english', sa.Integer(), nullable=True),
    sa.Column('physics', sa.Integer(), nullable=True),
    sa.Column('chemistry', sa.Integer(), nullable=True),
    sa.Column('history', sa.Integer(), nullable=True),
    sa.Column('geography', sa.Integer(), nullable=True),
    sa.Column('literature', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    # ### end Alembic commands ###
