"""Student-class relationship moved to class.id field.

Revision ID: 795ed456ba08
Revises: c832a5e73861
Create Date: 2025-02-19 07:38:07.331045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "795ed456ba08"
down_revision: Union[str, None] = "c832a5e73861"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("class_id", sa.Integer(), nullable=False))
    op.drop_constraint("fk_student_class_num", "students", type_="foreignkey")
    op.create_foreign_key(
        "fk_student_class_id", "students", "classes", ["class_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("students", "class_num")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students", sa.Column("class_num", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint("fk_student_class_id", "students", type_="foreignkey")
    op.create_foreign_key(
        "fk_student_class_num",
        "students",
        "classes",
        ["class_num"],
        ["class_num"],
        ondelete="CASCADE",
    )
    op.drop_column("students", "class_id")
    # ### end Alembic commands ###
