"""Add SubjectEnum to teachers.

Revision ID: f15b957cc320
Revises: 7c94ff28489f
Create Date: 2025-03-28 20:56:14.508530

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f15b957cc320'
down_revision: Union[str, None] = '7c94ff28489f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

subject_enum_values = [
    'Math', 'English', 'Physics', 'Chemistry', 'History', 'Geography', 'Literature'
]

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"CREATE TYPE subjectenum AS ENUM ({', '.join([repr(value) for value in subject_enum_values])})")

    op.add_column('marks', sa.Column('chemistry', sa.Integer(), nullable=False))
    op.drop_column('marks', 'science')
    op.add_column('teachers', sa.Column('subject', sa.Enum('MATH', 'ENGLISH', 'PHYSICS', 'CHEMISTRY', 'HISTORY', 'GEOGRAPHY', 'LITERATURE', name='subjectenum'), nullable=True))
    op.create_index(op.f('ix_teachers_subject'), 'teachers', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_subject'), table_name='teachers')
    op.drop_column('teachers', 'subject')
    op.add_column('marks', sa.Column('science', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('marks', 'chemistry')

    op.execute('DROP TYPE subjectenum')
    # ### end Alembic commands ###
