"""Create user-student and user-teacher tables relationships. Remove column role from students and teachers tables.

Revision ID: c832a5e73861
Revises: c673dfa660a3
Create Date: 2025-02-19 07:30:59.537011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c832a5e73861"
down_revision: Union[str, None] = "c673dfa660a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_student_user_id", "students", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("teachers", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_student_user_id", "teachers", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_student_user_id", "teachers", type_="foreignkey")
    op.drop_column("teachers", "user_id")
    op.drop_constraint("fk_student_user_id", "students", type_="foreignkey")
    op.drop_column("students", "user_id")
    # ### end Alembic commands ###
