"""Create teachers table.

Revision ID: 6b1886afd5a1
Revises: 1c3e667310e9
Create Date: 2025-01-26 13:50:22.110094

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b1886afd5a1"
down_revision: Union[str, None] = "1c3e667310e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teachers",
        sa.Column("class_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("second_name", sa.String(length=50), server_default="", nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"], ["classes.id"], name="fk_teacher_class_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("hashed_password"),
        sa.UniqueConstraint("username"),
    )
    op.drop_index("ix_classes_id", table_name="classes")
    op.drop_index("ix_students_id", table_name="students")
    op.drop_constraint("fk_student_class_num", "students", type_="foreignkey")
    op.create_foreign_key(
        "fk_student_class_num",
        "students",
        "classes",
        ["class_num"],
        ["class_num"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_student_class_num", "students", type_="foreignkey")
    op.create_foreign_key(
        "fk_student_class_num", "students", "classes", ["class_num"], ["class_num"]
    )
    op.create_index("ix_students_id", "students", ["id"], unique=False)
    op.create_index("ix_classes_id", "classes", ["id"], unique=False)
    op.drop_table("teachers")
    # ### end Alembic commands ###
